import { parseAbi } from "viem";

/**
 * Chamber ABI synced from loreum-org/chamber main
 * (`IChamber.sol`, `IWallet.sol`, `IBoard.sol`, ERC-20/4626, Pausable).
 *
 * Dropped (no longer emitted): DirectorshipChanged, QuorumUpdated.
 * SubmitTransaction still includes `bytes data` (IWallet).
 */
export const ChamberAbi = parseAbi([
  "function initialize(address erc20Token, address erc721Token, uint256 seats, string name, string symbol)",
  "function deposit(uint256 assets, address receiver) returns (uint256 shares)",
  "function mint(uint256 shares, address receiver) returns (uint256 assets)",
  "function withdraw(uint256 assets, address receiver, address owner) returns (uint256 shares)",
  "function redeem(uint256 shares, address receiver, address owner) returns (uint256 assets)",
  "function totalAssets() view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function asset() view returns (address)",
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function nft() view returns (address)",
  "function delegate(uint256 tokenId, uint256 amount)",
  "function undelegate(uint256 tokenId, uint256 amount)",
  "function getDelegations(address holder) view returns (uint256[] tokenIds, uint256[] amounts)",
  "function getHolderDelegation(address holder, uint256 tokenId) view returns (uint256 amount)",
  "function getTotalHolderDelegations(address holder) view returns (uint256 amount)",
  "function getDirectors() view returns (address[])",
  "function getMember(uint256 tokenId) view returns (uint256 nodeTokenId, uint256 amount, uint256 next, uint256 prev)",
  "function getTop(uint256 count) view returns (uint256[] tokenIds, uint256[] amounts)",
  "function getSize() view returns (uint256)",
  "function getQuorum() view returns (uint256)",
  "function getSeats() view returns (uint256)",
  "function getSeatedAt(uint256 tokenId) view returns (uint256 seatedAtBlock)",
  "function updateSeats(uint256 tokenId, uint256 numOfSeats)",
  "function executeSeatsUpdate(uint256 tokenId)",
  "function cancelSeatUpdate(uint256 tokenId)",
  "function submitTransaction(uint256 tokenId, address target, uint256 value, bytes data)",
  "function submitTransaction(uint256 tokenId, address target, uint256 value, bytes data, uint256 deadline)",
  "function confirmTransaction(uint256 tokenId, uint256 transactionId)",
  "function executeTransaction(uint256 tokenId, uint256 transactionId, bytes data)",
  "function revokeConfirmation(uint256 tokenId, uint256 transactionId)",
  "function cancelTransaction(uint256 tokenId, uint256 transactionId)",
  "function getTransactionCount() view returns (uint256)",
  "function getConfirmation(uint256 tokenId, uint256 nonce) view returns (bool)",
  "function getProxyAdmin() view returns (address adminContract)",
  "function paused() view returns (bool)",
  "function pause()",
  "function unpause()",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)",
  "event Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)",
  "event DelegationUpdated(address indexed holder, uint256 indexed tokenId, uint256 amount)",
  "event Delegate(address indexed sender, uint256 indexed tokenId, uint256 amount)",
  "event Undelegate(address indexed sender, uint256 indexed tokenId, uint256 amount)",
  "event SetSeats(uint256 indexed tokenId, uint256 numOfSeats)",
  "event ExecuteSetSeats(uint256 indexed tokenId, uint256 seats)",
  "event SeatUpdateCancelled(uint256 indexed tokenId)",
  "event SubmitTransaction(uint256 indexed tokenId, uint256 indexed nonce, address indexed to, uint256 value, bytes data)",
  "event ConfirmTransaction(uint256 indexed tokenId, uint256 indexed nonce)",
  "event RevokeConfirmation(uint256 indexed tokenId, uint256 indexed nonce)",
  "event ExecuteTransaction(uint256 indexed tokenId, uint256 indexed nonce)",
  "event CancelTransaction(uint256 indexed tokenId, uint256 indexed nonce)",
  "event TransactionCancelled(uint256 indexed nonce)",
  "event TransactionDeadlineSet(uint256 indexed nonce, uint256 deadline)",
  "event ProposalMetadataSet(uint256 indexed nonce, string metadataURI)",
  "event TransactionSubmitted(uint256 indexed transactionId, address indexed target, uint256 value)",
  "event TransactionConfirmed(uint256 indexed transactionId, address indexed confirmer)",
  "event TransactionExecuted(uint256 indexed transactionId, address indexed executor)",
  "event TransactionCancelVoted(uint256 indexed transactionId, address indexed voter)",
  "event Received(address indexed sender, uint256 amount)",
  "event ReceivedERC721(address indexed token, address indexed from, uint256 indexed tokenId)",
  "event Initialized(uint64 version)",
  "event Paused(address account)",
  "event Unpaused(address account)",
  "error InsufficientDelegatedAmount()",
  "error InsufficientChamberBalance()",
  "error ExceedsDelegatedAmount()",
  "error TransferToZeroAddress()",
  "error ArrayLengthsMustMatch()",
  "error NotEnoughConfirmations()",
  "error NotDirector()",
  "error DirectorNotSeated()",
  "error ZeroAddress()",
  "error ZeroAmount()",
  "error ZeroTokenId()",
  "error InvalidTokenId()",
  "error ZeroSeats()",
  "error TooManySeats()",
  "error InvalidTransaction()",
  "error NotAuthorized()",
  "error AssetAmountMismatch()",
  "error EnforcedPause()",
  "error ExpectedPause()",
  "error TransactionExpired()",
  "error InvalidDeadline()",
]);
